Event permissions
raccoongang/edx-calendar-tab pull request #1
Opened 2017-05-31 14:54 UTC by wowkalucky

2017-06-06 15:12 UTC, z4y4ts requested changes
Looks good in general.  Few things need to be addressed before a merge.
Also, please address CodeClimate complaints.

2017-06-06 15:12 UTC, z4y4ts commented on calendar_tab/models.py
> +@python_2_unicode_compatible
👍

2017-06-06 15:12 UTC, z4y4ts commented on calendar_tab/static/calendar_tab/js/calendar-tab.js
> +    function block_readonly(id) {
Add JsDoc for this function

2017-06-06 15:12 UTC, z4y4ts commented on calendar_tab/templates/calendar_tab/500_fragment.html
> +## mako
Can we have a Django templates, not Mako?

2017-06-06 15:12 UTC, z4y4ts commented on calendar_tab/views.py
> +    Example: "2017-04-25T16:00:00-04:00" >> "04/25/2017 16:00"
It looks like you're losing timezone here.

2017-06-06 15:12 UTC, z4y4ts commented on calendar_tab/views.py
> +    calendar_id = course_calendar_data[0].get('calendar_id') if course_calendar_data else ''
If Course can have only one calendar, you can use `.first()` here.

2017-06-06 15:12 UTC, z4y4ts commented on calendar_tab/views.py
> +    """Returns the default template context for rendering calendar view.
Here and everywhere, please use edx-style docstrings.
```py
"""
Sample docstring.
"""
```

2017-06-06 15:12 UTC, z4y4ts commented on calendar_tab/views.py
> +        dependencies.update(self.get_js_dependencies('calendar_tab_vendor'))
You can pass `self.get_js_dependencies('calendar_tab_vendor')` directly to the `set()` on previous line.

2017-06-06 15:12 UTC, z4y4ts commented on calendar_tab/views.py
> +    def css_dependencies(self):
So am I reading this correctly, the only purpose to have this function is to make Django's dev mode work correctly?

2017-06-06 15:12 UTC, z4y4ts commented on calendar_tab/views.py
> +            'description': post_data.get('description') or '',
Why don't you write `.get('description', '')` instead of `or ''`?

2017-06-06 15:12 UTC, z4y4ts commented on calendar_tab/views.py
> +def dataprocessor_view(request, course_id):
Split this function into smaller ones.
Optionally, move to separate file.

2017-06-06 15:12 UTC, z4y4ts commented on setup.py
> +    description='Open Edx Calendar tab (based on Google Calendar service',
Trailing `)`

2017-06-07 08:23 UTC, wowkalucky commented on calendar_tab/views.py
> +    calendar_id = course_calendar_data[0].get('calendar_id') if course_calendar_data else ''
Таки да...

2017-06-07 08:24 UTC, wowkalucky commented on calendar_tab/static/calendar_tab/js/calendar-tab.js
> +    function block_readonly(id) {
Got it.

2017-06-07 08:43 UTC, wowkalucky commented on calendar_tab/views.py
> +    """Returns the default template context for rendering calendar view.
Got it.

2017-06-07 08:47 UTC, wowkalucky commented on calendar_tab/views.py
> +        dependencies.update(self.get_js_dependencies('calendar_tab_vendor'))
Ok. (This code was from generic web-fragments example).

2017-06-07 15:58 UTC, wowkalucky commented on calendar_tab/templates/calendar_tab/500_fragment.html
> +## mako
Not sure, but it seems like "yes".

2017-06-09 09:20 UTC, z4y4ts requested changes

2017-06-09 09:20 UTC, z4y4ts commented on calendar_tab/views.py
> +from dateutil import parser
Add this requirement to `setup.py`

2017-06-09 09:20 UTC, z4y4ts commented on README.md
> +**NOTE:** this is a draft README for not fully implemented yet feature.
This is not a draft anymore.

2017-06-09 09:20 UTC, z4y4ts commented on README.md
> +
Also, fix all markdownlint complaints for this file.
See here -- https://codeclimate.com/github/raccoongang/edx-calendar-tab/pull/1

2017-06-09 09:20 UTC, z4y4ts commented on README.md
> +1) INSTALLATION
`# Installation` -- So one can link to this specific section.

2017-06-09 09:20 UTC, z4y4ts commented on README.md
> +1.1) Install Package
`## Install Package`

2017-06-09 09:20 UTC, z4y4ts commented on README.md
> +installing manually for evaluation and testing:
Capitalize first letter

2017-06-09 09:20 UTC, z4y4ts commented on README.md
> +    sudo su - edxapp -s /bin/bash
`sudo -sHu edxapp`

2017-06-09 09:20 UTC, z4y4ts commented on README.md
> +    pip install -e git+https://github.com/raccoongang/edx-calendar-tab.git@wowkalucky/event_permissions#egg=edx-calendar-tab
Change link to `git+https://github.com/raccoongang/edx-calendar-tab.git#egg=edx-calendar-tab`

2017-06-09 09:20 UTC, z4y4ts commented on README.md
> +1.2) Production installation
`##`

2017-06-09 09:20 UTC, z4y4ts commented on README.md
> +#TBD
Write this section.

2017-06-09 09:20 UTC, z4y4ts commented on README.md
> +In "/edx/app/edxapp/edx-platform/lms/envs/common.py" add
This is very inconvenient. Please change so there's no need to edit `common.py` file.

2017-06-09 09:20 UTC, z4y4ts commented on README.md
> +In "/edx/app/edxapp/edx-platform/lms/urls.py" add __before__ static_tab urls:
Same here. A requirement to edit `lms/urls.py` after the installation is very inconvenient.
Change so there's no need to edit it.

2017-06-09 09:20 UTC, z4y4ts commented on README.md
> +2.2) Configure google service account
Move this section up, so by the time you need to add
```
"GOOGLE_CALENDAR_TAB_PRIVATE_KEY_URL": "/edx/app/edxapp/edx-calendar-tab-google-api-private-key.json"
```
to `lms.envs.json` one already has that file.

2017-06-09 09:20 UTC, z4y4ts commented on README.md
> +2.2) Configure google service account
And also `2.2)` -> `##`

2017-06-09 09:20 UTC, z4y4ts commented on README.md
> +3) BASIC USAGE
`3)` -> `#`

2017-06-09 09:20 UTC, z4y4ts commented on README.md
> +  Students can't update/delete event they not own.
`don't own.`

2017-06-09 12:26 UTC, wowkalucky commented on README.md
> +In "/edx/app/edxapp/edx-platform/lms/urls.py" add __before__ static_tab urls:
I see it, but not sure I know the way to avoid extending 'INSTALLED_APPS' and 'urlpatterns' during our app installation...

2017-06-12 09:40 UTC, z4y4ts requested changes

2017-06-12 09:40 UTC, z4y4ts commented on README.md
> +
Remove blank line

2017-06-12 09:40 UTC, z4y4ts commented on README.md
> + TBD
Write this section.

2017-06-12 09:40 UTC, z4y4ts commented on README.md
> +In "/edx/app/edxapp/edx-platform/lms/envs/common.py" add
I don't see any update here

2017-06-12 09:40 UTC, z4y4ts commented on README.md
> +In "/edx/app/edxapp/edx-platform/lms/urls.py" add __before__ static_tab urls:
`INSTALLED_APPS` is fine. `urlpatterns` should be handled by application itself.

2017-06-12 09:40 UTC, z4y4ts commented on README.md
> +  From the very beginning after calendar tab is enabled, there is no
Please remove leading spaces for this section.

2017-06-12 09:40 UTC, z4y4ts commented on README.md
> +  As the OpenEdx [documentation](https://openedx.atlassian.net/wiki/display/AC/Adding+a+new+course+tab) says:
Change `OpenEdx [documentation](https://openedx.atlassian.net/wiki/display/AC/Adding+a+new+course+tab)`
to `[Open edX documentation]`
and below the paragraph add `[Open edX documentation]:
 https://openedx.atlassian.net/wiki/display/AC/Adding+a+new+course+tab`

2017-06-12 09:41 UTC, z4y4ts commented
Also, there are still unfixed issues in README.md. Fix them before merge.

2017-06-12 14:53 UTC, wowkalucky commented on README.md
> +In "/edx/app/edxapp/edx-platform/lms/envs/common.py" add
Please, check [this](https://github.com/raccoongang/edx-calendar-tab/blob/wowkalucky/auto_templates/calendar_tab/__init__.py) out.

2017-06-14 12:16 UTC, wowkalucky commented
CodeClimate still complains, but there is no any complaints which could prevent the merging.
And I'm not authorized to perform the merging.

2017-06-15 09:09 UTC, z4y4ts approved these changes

2017-06-15 09:31 UTC, merged